title: IshikuraDB
description: High-performance, ACID-compliant database written in C++

theme: minima
show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

baseurl: /ishikura-db

header_pages:
  - index.md
  - api.md
  - architecture.md
  - security.md

github:
  repository_url: https://github.com/arcbjorn/cpp-ondisk-nosql-db