title: IshikuraDB Documentation
description: High-performance, ACID-compliant database written in C++

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

baseurl: /ishikura-db

github:
  repository_url: https://github.com/arcbjorn/cpp-ondisk-nosql-db